### PR TITLE
Experience company link added

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
Hi @arifszn 

Description:

Experience section's company name clickable added to redirect to company page is it has in new tab
Please add `hacktoberfest-accepted` label 

Issue: #195 

Checklist:
1. readme updated
2. Link made optional
3. updated props
4. updated types/index.d.ts

### CODE REVIEW

**Comment by arifszn** [comment]
Thanks for the PR. Will review it soon.

**Comment by arifszn** [comment]
@jsvigneshkanna please fix the linting error. 
https://github.com/arifszn/gitprofile/actions/runs/3227038117/jobs/5330702374

**Comment by jsvigneshkanna** [comment]
@arifszn ,

I have fixed the prettier linting errors. please check now

BTW, i would suggest you to add 
`'prettier/prettier': ['error', { endOfLine: 'auto' }],` under rules section in .eslintrc.js as we are seeing many false errors like `Delete cr`

**Comment by arifszn** [comment]
Thanks. Noted.

**Comment by arifszn** [comment]
> @arifszn Can you explain whats the issue in github action

`npm run prettier:fix` should solve it.

**Comment by jsvigneshkanna** [comment]
@arifszn ,

Should I need to run that cmd?

**Review by arifszn — APPROVED** [review]

**Pull request merged**
