### PR TITLE
Add Discord as social link

### LINKED ISSUE #380: Adding discord link
Adding discord link and Hashnode link in the social link

### PR DESCRIPTION
**Pull request by nathen418**
This PR adds the option to include a Discord server link in the social links section.
Currently, the text that is displayed is the invite code as I didn't have a better idea of what to display for the link title. Feel free to suggest something else.

Partially resolves #380

### CODE REVIEW

**Comment by arifszn** [comment]
@nathen418 I was thinking about how we can solve the issue with the link as the current implementation does not produce any valid link to the Discord profile. I was thinking like this:
```js
discord: {
  displayName: 'john',
  userId: 123123123,
},
```

Let me know what do you think?

**Comment by nathen418** [comment]
So what would the clickable link be? Or would this option omit one? 

The reason for how I structured the option to display an invite code and link to an invite was because there isn't a way to get a link to a discord user's profile unless you do something like `discord://-/users/603629606154666024` which only seems to work on mac and windows and only if you are friends with the user and the application is registered as a uri handler for the `discord://` protocol. At the moment I handle this by [doing this](https://github.com/nathen418/nathen418.com/blob/main/src/components/details/index.jsx#L241) manually which is not ideal.

If we don't need a link to a profile or something then I think doing 
``` js
discord: {
  displayName: 'john',
  userId: 123123123,
},
``` 
in `gitprofile.config.js` is a fine way to do things, I would just suggest changing `displayName` to `userName` as this is the user's actual semi-permanent username

**Comment by arifszn** [comment]
We would have a link. I was thinking like this: https://discordapp.com/users/515878023111901184. If you visit the link, can you find my profile?

**Comment by arifszn** [comment]
Also, discord://-/users/603629606154666024 does not seem to do anything on my end. I am on windows machine and I don't have the discord app installed.

**Comment by nathen418** [comment]
> We would have a link. I was thinking like this: https://discordapp.com/users/515878023111901184. If you visit the link, can you find my profile?

Since I am not friends with you on Discord that link just redirects to https://discord.com/channels/@me so that won't work and I guess neither will my discord:// way apparently

**Comment by arifszn** [comment]
Ah bummer. Then we should find another approach. How about when the user clicks on the discord name, it copies the username only and we display a popup notification saying the username is copied?

**Comment by nathen418** [comment]
Yeah I like that idea. I can throw together an update to the pr in a few hours.

**Comment by arifszn** [comment]
Closing due to inactivity.

**Pull request closed without merging**
