### PR TITLE
Add social links - Reddit, Threads, Udemy

### PR DESCRIPTION
**Pull request by Programer3**
Passed the linter check and working as expected locally. Also, there are some minor Readme Changes and code clean-ups

### CODE REVIEW

**Comment by arifszn** [comment]
Thanks. Will check it asap.

**Comment by Programer3** [comment]
Hey just wanted to tell you that this is my first time working with react and typescript

**Review by arifszn — APPROVED** [review]
Nice work! Thanks for the contribution.

**Comment by Programer3** [comment]
Thank you so much, This was a great leaning Experience

**Pull request merged**
