### PR TITLE
Add a Certifications section

### PR DESCRIPTION
**Pull request by nathen418**
Description:

Adds a certifications section to the profile page to display industry certifications.

Issue: https://github.com/arifszn/gitprofile/issues/233

### CODE REVIEW

**Comment by arifszn** [comment]
Thanks for the PR. Will look into it soon.

**Review by arifszn — CHANGES_REQUESTED** [review]
An optional link to the certificate will be helpful.

**Comment by nathen418** [comment]
Bumping this. Should I add anything else or is this good?

**Comment by arifszn** [comment]
Sorry, I was on vacation. Will review it tonight. :raised_hands:

**Review by arifszn — APPROVED** [review]

**Pull request merged**
